# Generated by Django 3.2.12 on 2022-02-21 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nivelAcesso', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=500)),
                ('prazo', models.DateTimeField()),
                ('dataInicio', models.DateTimeField(default=datetime.datetime(2022, 2, 21, 15, 26, 33, 443927, tzinfo=utc))),
                ('dataFim', models.DateTimeField(blank=True, null=True)),
                ('idAmbienteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ambientes')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('idUserFK', models.BigIntegerField()),
                ('email', models.CharField(max_length=80)),
                ('fone', models.CharField(max_length=15)),
                ('ativo', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.upload_image_user)),
                ('idNivelAcessoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cargos')),
            ],
        ),
        migrations.CreateModel(
            name='TarefasUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTarefaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tarefas')),
                ('idUsuarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='TarefasStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('idStatusFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
                ('idTarefaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tarefas')),
            ],
        ),
        migrations.AddField(
            model_name='tarefas',
            name='idSolicitanteFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuarios'),
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.upload_image_task)),
                ('idStatusFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
                ('idTarefaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tarefas')),
            ],
        ),
    ]
