# Generated by Django 3.2.12 on 2022-03-31 07:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='idStatusFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.status'),
        ),
        migrations.AddField(
            model_name='tarefasstatus',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='uid',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='idStatusFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='idTarefaFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tarefas'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=main.models.upload_image_task),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='nome',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 31, 7, 49, 25, 434806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tarefasstatus',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 31, 7, 49, 25, 435814, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='idNivelAcessoFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='main.cargos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='idUserFK',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
