# Generated by Django 3.2.12 on 2022-02-10 03:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 3, 48, 57, 890870, tzinfo=utc)),
        ),
    ]
