# Generated by Django 3.2.12 on 2022-02-10 04:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tarefas_datainicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nivelAcesso',
            new_name='nivelAcessoFK',
        ),
        migrations.AddField(
            model_name='cargos',
            name='nivelAcesso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 4, 23, 1, 994590, tzinfo=utc)),
        ),
    ]
