# Generated by Django 3.2.12 on 2022-02-22 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220222_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefasstatus',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='tarefasusuarios',
            name='nome',
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 12, 10, 6, 594449, tzinfo=utc)),
        ),
    ]
