# Generated by Django 3.2.12 on 2022-02-22 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220222_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 15, 32, 8, 840611, tzinfo=utc)),
        ),
    ]
