# Generated by Django 3.2.12 on 2022-02-22 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tarefas_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='idStatusFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='idTarefaFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tarefas'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='nome',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 17, 51, 47, 884430, tzinfo=utc)),
        ),
    ]
