# Generated by Django 3.2.12 on 2022-02-11 00:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tarefas_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 0, 26, 27, 89559, tzinfo=utc)),
        ),
    ]
