# Generated by Django 3.2.12 on 2022-02-22 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220222_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fototeste',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=main.models.upload_image_teste),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 19, 18, 6, 574076, tzinfo=utc)),
        ),
    ]
