# Generated by Django 3.2.12 on 2022-02-11 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tarefas_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 5, 42, 47, 215585, tzinfo=utc)),
        ),
    ]
