# Generated by Django 3.2.12 on 2022-02-11 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tarefas_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 18, 49, 5, 997896, tzinfo=utc)),
        ),
    ]
