# Generated by Django 3.2.12 on 2022-02-23 00:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220222_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotoTeste',
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 0, 50, 45, 732770, tzinfo=utc)),
        ),
    ]
