# Generated by Django 3.2.12 on 2022-02-17 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_tarefas_datainicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='idResponsavelFK',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_image_user),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 14, 55, 8, 433086, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='idSolicitanteFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuarios'),
        ),
        migrations.CreateModel(
            name='TarefasUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTarefaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tarefas')),
                ('idUsuarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuarios')),
            ],
        ),
    ]
