# Generated by Django 3.2.12 on 2022-02-25 16:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220224_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 16, 13, 28, 30776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tarefasstatus',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 25, 16, 13, 28, 31775, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='idNivelAcessoFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cargos'),
        ),
    ]
