# Generated by Django 3.2.12 on 2022-02-17 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220217_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nivelAcessoFK',
            new_name='idNivelAcessoFK',
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 15, 9, 24, 656912, tzinfo=utc)),
        ),
    ]
