# Generated by Django 3.2.12 on 2022-02-25 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220225_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 25, 18, 43, 26, 645724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tarefasstatus',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 25, 18, 43, 26, 646724, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='idNivelAcessoFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='main.cargos'),
        ),
    ]
