# Generated by Django 3.2.12 on 2022-02-19 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220217_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 17, 37, 54, 972831, tzinfo=utc)),
        ),
    ]
