# Generated by Django 3.2.12 on 2022-03-02 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220225_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.status'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 6, 16, 54, 878042, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tarefasstatus',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 2, 6, 16, 54, 880042, tzinfo=utc), null=True),
        ),
    ]
