# Generated by Django 3.2.12 on 2022-03-07 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20220302_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dataInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 12, 2, 54, 811876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tarefasstatus',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 7, 12, 2, 54, 812875, tzinfo=utc), null=True),
        ),
    ]
